version: '3.8'
services:
  app:
    container_name: 'zakat-app'
    image: zakat
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3033:3033"
    depends_on:
      - db
    networks:
      - backend

  db:
    container_name: zakat-db
    image: postgres:14.7-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zdb
    networks:
      - backend

networks:
  backend:
    driver: bridge
