-- liquibase formatted sql

-- changeset katyshev:init
CREATE TABLE IF NOT EXISTS price_item
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    dist character varying(50),
    code_pst character varying(50),
    name character varying(100),
    mnn character varying(100),
    country character varying(100),
    manufacturer character varying(100),
    qnt_pack integer,
    ean13 character varying(30),
    nds double precision,
    g_date character varying(100),
    quantity integer,
    price numeric(10,2),
    mark integer,
    in_order integer,
    CONSTRAINT price_item_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS uniko_lec_item
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_group integer,
    tmc integer,
    quantity double precision,
    name character varying(100),
    factory character varying(50),
    short_name character varying(50),
    ordered integer,
    CONSTRAINT uniko_lec_item_pkey PRIMARY KEY (id)
);

CREATE TABLE order_item
(
    order_item_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    price_item_id integer NOT NULL REFERENCES price_item(id),
    in_order integer,
    create_time timestamp,
    export_time timestamp,
    CONSTRAINT order_item_pkey PRIMARY KEY (order_item_id)
);

CREATE TABLE archive_item
(
    archive_item_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_number INTEGER NOT NULL,
    price_name VARCHAR(100) NOT NULL,
    price numeric(10,2),
    quantity INTEGER NOT NULL,
    export_time timestamp
)