-- liquibase formatted sql

-- changeset katyshev:init
CREATE TABLE IF NOT EXISTS price_item
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    dist character varying(50),
    code_pst character varying(50),
    name character varying(100),
    mnn character varying(100),
    country character varying(100),
    manufacturer character varying(100),
    qnt_pack integer,
    ean13 character varying(30),
    nds double precision,
    g_date character varying(100),
    quantity integer,
    price numeric(10,2),
    mark integer,
    in_order integer,
    CONSTRAINT price_item_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS uniko_lec_item
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_group integer,
    tmc integer,
    quantity double precision,
    name character varying(100),
    factory character varying(50),
    short_name character varying(50),
    ordered integer,
    CONSTRAINT uniko_lec_item_pkey PRIMARY KEY (id)
);

CREATE TABLE order_item
(
    order_item_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    price_item_id integer NOT NULL REFERENCES price_item(id),
    in_order integer,
    create_time timestamp,
    export_time timestamp,
    CONSTRAINT order_item_pkey PRIMARY KEY (order_item_id)
);

CREATE TABLE archive_item
(
    archive_item_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_number INTEGER NOT NULL,
    price_name VARCHAR(100) NOT NULL,
    price numeric(10,2),
    quantity INTEGER NOT NULL,
    export_time timestamp
)

-- changeset katyshev:population database

INSERT INTO public.price_item (id, dist, code_pst, name, mnn, country, manufacturer, qnt_pack, ean13, nds, g_date, quantity, price, mark, in_order) VALUES (1, 'Протек.dbf', '241467', '!АБРИКОСОВАЯ МАСКА 50МЛ', '', 'Франция', 'Academie Scientifique', 0, '3145072024091', 20, 'Sun Feb 01 00:00:00 MSK 2026', 1, 2154.80, 0, 0);
INSERT INTO public.price_item (id, dist, code_pst, name, mnn, country, manufacturer, qnt_pack, ean13, nds, g_date, quantity, price, mark, in_order) VALUES (2, 'Протек.dbf', '241505', '!ЗАЩИТНЫЙ КАРАНДАШ ДЛЯ ЧУВСТВИТЕЛЬНЫХ ЗОН SPF 50+ 10 МЛ', '', 'Франция', 'Academie Scientifique', 0, '3145070410001', 20, 'Sat Mar 01 00:00:00 MSK 2025', 1, 3600.50, 0, 0);
INSERT INTO public.price_item (id, dist, code_pst, name, mnn, country, manufacturer, qnt_pack, ean13, nds, g_date, quantity, price, mark, in_order) VALUES (3, 'Протек.dbf', '241470', '!ОЧИЩАЮЩИЙ КРЕМ ЮВАНИЛ 50 МЛ', '', 'Франция', 'Франция', 0, '3145070803001', 20, 'Tue Jul 01 00:00:00 MSK 2025', 1, 5157.72, 0, 0);
INSERT INTO public.price_item (id, dist, code_pst, name, mnn, country, manufacturer, qnt_pack, ean13, nds, g_date, quantity, price, mark, in_order) VALUES (4, 'Протек.dbf', '241466', '!СОЛНЦЕЗАЩИТНЫЙ СПРЕЙ ДЛЯ ЧУВСТВИТЕЛЬНОЙ КОЖИ SPF 50+ 150 МЛ', '', 'Франция', 'Academie Scientifique', 0, '3145070424008', 20, 'Mon Jul 01 00:00:00 MSK 2024', 1, 7325.02, 0, 0);
INSERT INTO public.price_item (id, dist, code_pst, name, mnn, country, manufacturer, qnt_pack, ean13, nds, g_date, quantity, price, mark, in_order) VALUES (5, 'Протек.dbf', '241479', '!УВЛАЖНЯЮЩАЯ СЫВОРОТКА 24 ЧАСА, 30 МЛ', '', '', 'Academie Scientifique', 0, '', 20, 'Mon Apr 01 00:00:00 MSK 2024', 1, 8045.12, 0, 0);
INSERT INTO public.price_item (id, dist, code_pst, name, mnn, country, manufacturer, qnt_pack, ean13, nds, g_date, quantity, price, mark, in_order) VALUES (6, 'Протек.dbf', '236316', '"КОНТИНЕНТ КРАСОТЫ "ЖИДКОСТЬ АНТИСЕПТИЧЕСКАЯ С КАЛЬЦИЕМ ФЛ. С РАСПЫЛ. 250МЛ', '', 'Россия', 'Бахир ООО', 36, '', 20, 'Sat Apr 01 00:00:00 MSK 2023', 356, 206.84, 0, 0);
INSERT INTO public.price_item (id, dist, code_pst, name, mnn, country, manufacturer, qnt_pack, ean13, nds, g_date, quantity, price, mark, in_order) VALUES (7, 'Протек.dbf', '312863', '"НЕЙРО В+" КАПС. 768МГ №30 (БАД)', '', 'Сербия', 'Элефант Ко', 270, '', 20, 'Thu Dec 01 00:00:00 MSK 2022', 243, 554.96, 0, 0);
INSERT INTO public.price_item (id, dist, code_pst, name, mnn, country, manufacturer, qnt_pack, ean13, nds, g_date, quantity, price, mark, in_order) VALUES (8, 'Протек.dbf', '280777', '"РЕНЕССАНС. ЛЮТЕИН 10МГ" КАПС. 0,25МГ №30 (БАД)', '', 'Россия', 'Марбиофарм ОАО', 114, '4602876007013', 20, 'Sun Jan 01 00:00:00 MSK 2023', 78, 501.07, 0, 0);
INSERT INTO public.price_item (id, dist, code_pst, name, mnn, country, manufacturer, qnt_pack, ean13, nds, g_date, quantity, price, mark, in_order) VALUES (9, 'Протек.dbf', '60312863', '"НЕЙРО В+" КАПС. 768МГ №30 (БАД)', '', 'Сербия', 'Элефант Ко', 270, '', 20, 'Thu Dec 01 00:00:00 MSK 2022', 243, 560.49, 0, 0);
INSERT INTO public.price_item (id, dist, code_pst, name, mnn, country, manufacturer, qnt_pack, ean13, nds, g_date, quantity, price, mark, in_order) VALUES (10, 'Протек.dbf', '231275', '"ЧИНЧ" КАПС. 0,32Г №60 (БАД)', '', 'Россия', 'Фармакор Продакшн ООО', 28, '4603569722213', 20, 'Wed Jan 31 00:00:00 MSK 2024', 184, 473.14, 0, 0);

INSERT INTO public.uniko_lec_item (id, order_group, tmc, quantity, name, factory, short_name, ordered) VALUES (1, 2007, 8182, 11, 'Валерианы экстр 20мг №50 драже', '', NULL, 0);
INSERT INTO public.uniko_lec_item (id, order_group, tmc, quantity, name, factory, short_name, ordered) VALUES (2, 2127, 61675, 1, 'Веторон Е 2%-20мл капли', '', NULL, 0);
INSERT INTO public.uniko_lec_item (id, order_group, tmc, quantity, name, factory, short_name, ordered) VALUES (3, 2131, 31040, 1, 'Виагра 100мг №1 тб.', '', NULL, 0);
INSERT INTO public.uniko_lec_item (id, order_group, tmc, quantity, name, factory, short_name, ordered) VALUES (4, 2232, 890, 1, 'Витаон 50мл фл.', '', NULL, 0);
INSERT INTO public.uniko_lec_item (id, order_group, tmc, quantity, name, factory, short_name, ordered) VALUES (5, 2357, 38, 1, 'Аджисепт класс №24 паст.', '', NULL, 0);
INSERT INTO public.uniko_lec_item (id, order_group, tmc, quantity, name, factory, short_name, ordered) VALUES (6, 2450, 11531, 1, 'Акридерм ГК 15г крем', '', NULL, 0);
INSERT INTO public.uniko_lec_item (id, order_group, tmc, quantity, name, factory, short_name, ordered) VALUES (7, 3741, 418, 1, 'Бейби Калм 5/50мл капли', '', NULL, 0);
INSERT INTO public.uniko_lec_item (id, order_group, tmc, quantity, name, factory, short_name, ordered) VALUES (8, 4509, 33076, 1, 'Вербена Шалфей карамель 60г', '', NULL, 0);
INSERT INTO public.uniko_lec_item (id, order_group, tmc, quantity, name, factory, short_name, ordered) VALUES (9, 5658, 24408, 1, 'Детралекс №30 тб.', '', NULL, 0);
INSERT INTO public.uniko_lec_item (id, order_group, tmc, quantity, name, factory, short_name, ordered) VALUES (10, 5726, 27433, 1, 'Дибазол 20мг №10 тб.', '', NULL, 0);
INSERT INTO public.uniko_lec_item (id, order_group, tmc, quantity, name, factory, short_name, ordered) VALUES (11, 5976, 6893, 3, 'Дриптан 5мг №30 тб.', '', NULL, 0);
INSERT INTO public.uniko_lec_item (id, order_group, tmc, quantity, name, factory, short_name, ordered) VALUES (12, 6578, 27221, 10, 'Йода спирт р-р 5%-25мл фл.', '', NULL, 0);
INSERT INTO public.uniko_lec_item (id, order_group, tmc, quantity, name, factory, short_name, ordered) VALUES (13, 6608, 33289, 7, 'Календулы настойка 40мл фл.', '', NULL, 0);

INSERT INTO public.archive_item (archive_item_id, order_number, price_name, price, quantity, export_time) VALUES (1, 1, 'Виагра табл п/о плен 25 мг х1', 685.70, 5, '2024-04-17 17:18:28.550751');
INSERT INTO public.archive_item (archive_item_id, order_number, price_name, price, quantity, export_time) VALUES (2, 1, 'Виагра табл п/о плен 25 мг х1', 685.70, 10, '2024-04-17 17:18:28.550751');
INSERT INTO public.archive_item (archive_item_id, order_number, price_name, price, quantity, export_time) VALUES (3, 1, 'Виагра табл п/о плен 25 мг х1', 685.70, 1, '2024-04-17 17:18:28.550751');
INSERT INTO public.archive_item (archive_item_id, order_number, price_name, price, quantity, export_time) VALUES (4, 1, 'ВИАГРА 0,025 N1 ТАБЛ П/ПЛЕН/ОБОЛОЧ', 696.26, 5, '2024-04-17 17:18:28.550751');
INSERT INTO public.archive_item (archive_item_id, order_number, price_name, price, quantity, export_time) VALUES (5, 1, 'Виагра табл п/о плен 25 мг х1', 685.70, 5, '2024-04-17 17:19:49.569262');
INSERT INTO public.archive_item (archive_item_id, order_number, price_name, price, quantity, export_time) VALUES (6, 1, 'Виагра табл п/о плен 25 мг х1', 685.70, 10, '2024-04-17 17:19:49.569262');
INSERT INTO public.archive_item (archive_item_id, order_number, price_name, price, quantity, export_time) VALUES (7, 1, 'Виагра табл п/о плен 25 мг х1', 685.70, 1, '2024-04-17 17:19:49.569262');
INSERT INTO public.archive_item (archive_item_id, order_number, price_name, price, quantity, export_time) VALUES (8, 1, 'ВИАГРА 0,025 N1 ТАБЛ П/ПЛЕН/ОБОЛОЧ', 696.26, 5, '2024-04-17 17:19:49.569262');

-- changeset katyshev:addUserRequestTable

CREATE TABLE user_request
(
    order_group_id INTEGER NOT NULL,
    user_request VARCHAR(100)
)

-- changeset katyshev:editUserRequestTable
ALTER TABLE user_request ADD PRIMARY KEY (order_group_id);

-- changeset katyshev:populationUserRequestTable

INSERT INTO public.user_request (order_group_id, user_request) VALUES (1, 'Test1');
INSERT INTO public.user_request (order_group_id, user_request) VALUES (2, 'Test2');
INSERT INTO public.user_request (order_group_id, user_request) VALUES (3, 'Test3');